// Copyright (C) LEGO System A/S - All Rights Reserved
// Unauthorized copying of this file, via any medium is strictly prohibited
// Place this file in: Editor/Utilities/BrickDecoupler.cs

using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

namespace LEGOModelImporter
{
    /// <summary>
    /// Utility class for decoupling bricks from their parent model groups
    /// </summary>
    public static class BrickDecoupler
    {
        /// <summary>
        /// Decouples a brick from its current parent and creates a new Model > ModelGroup hierarchy
        /// </summary>
        /// <param name="brick">The brick to decouple</param>
        /// <returns>The newly created ModelGroup containing the brick</returns>
        public static ModelGroup DecoupleBrick(Brick brick)
        {
            if (brick == null)
            {
                Debug.LogError("Cannot decouple null brick");
                return null;
            }

            // Check if lock bricks setting is enabled
            if (ToolsSettings.LockBricksAfterPlacement)
            {
                Debug.LogWarning("Cannot decouple brick - Lock Bricks After Placement is enabled. Disable it in LEGO Tools > Brick Building Settings");
                return null;
            }

            var currentModelGroup = brick.GetComponentInParent<ModelGroup>();
            if (currentModelGroup == null)
            {
                Debug.LogError("Brick is not part of a ModelGroup");
                return null;
            }

            // Safety check - don't decouple if brick is already in an auto-generated group
            if (currentModelGroup.autoGenerated && currentModelGroup.transform.childCount == 1)
            {
                Debug.LogWarning("Brick is already in its own auto-generated ModelGroup");
                return currentModelGroup;
            }

            try
            {
                // Record undo
                Undo.IncrementCurrentGroup();
                int undoGroup = Undo.GetCurrentGroup();
                Undo.SetCurrentGroupName("Decouple Brick");

                // Disconnect the brick from other bricks
                brick.DisconnectAll();

                // Store brick's world transform
                Vector3 worldPosition = brick.transform.position;
                Quaternion worldRotation = brick.transform.rotation;
                Vector3 worldScale = brick.transform.localScale;

                // Create new Model GameObject
                GameObject newModelGO = new GameObject($"Model_{brick.designID}");
                Undo.RegisterCreatedObjectUndo(newModelGO, "Create Model");
                
                // Add Model component
                Model newModel = newModelGO.AddComponent<Model>();
                newModel.autoGenerated = true;
                newModel.pivot = Model.Pivot.Original;
                
                // Add LEGOModelAsset component
                LEGOModelAsset modelAsset = newModelGO.AddComponent<LEGOModelAsset>();
                
                // Create new ModelGroup GameObject as child
                GameObject newModelGroupGO = new GameObject($"Group_{brick.designID}");
                Undo.RegisterCreatedObjectUndo(newModelGroupGO, "Create ModelGroup");
                Undo.SetTransformParent(newModelGroupGO.transform, newModelGO.transform, "Parent ModelGroup");
                
                // Add ModelGroup component
                ModelGroup newModelGroup = newModelGroupGO.AddComponent<ModelGroup>();
                newModelGroup.autoGenerated = true;
                newModelGroup.groupName = $"Decoupled_{brick.designID}";
                newModelGroup.parentName = newModel.name;
                newModelGroup.number = 0;
                newModelGroup.processed = false;
                
                // Copy import settings from original group if available
                if (currentModelGroup.importSettings != null)
                {
                    newModelGroup.importSettings = new ModelGroupImportSettings
                    {
                        colliders = currentModelGroup.importSettings.colliders,
                        connectivity = currentModelGroup.importSettings.connectivity,
                        isStatic = currentModelGroup.importSettings.isStatic,
                        lightmapped = currentModelGroup.importSettings.lightmapped,
                        randomizeRotation = currentModelGroup.importSettings.randomizeRotation,
                        lod = currentModelGroup.importSettings.lod
                    };
                }
                
                // Add LEGOModelGroupAsset component
                LEGOModelGroupAsset groupAsset = newModelGroupGO.AddComponent<LEGOModelGroupAsset>();
                
                // Move brick to new ModelGroup
                Undo.SetTransformParent(brick.transform, newModelGroupGO.transform, "Move Brick");
                
                // Restore world transform
                brick.transform.position = worldPosition;
                brick.transform.rotation = worldRotation;
                brick.transform.localScale = worldScale;
                
                // Position the Model at the brick's position
                newModelGO.transform.position = worldPosition;
                
                Undo.CollapseUndoOperations(undoGroup);
                
                Debug.Log($"Decoupled brick {brick.designID} into new Model > ModelGroup hierarchy");
                
                return newModelGroup;
            }
            catch (System.Exception e)
            {
                Debug.LogError($"Failed to decouple brick: {e.Message}");
                return null;
            }
        }

        /// <summary>
        /// Decouples multiple bricks, creating separate Model > ModelGroup hierarchies for each
        /// </summary>
        /// <param name="bricks">The bricks to decouple</param>
        /// <returns>List of newly created ModelGroups</returns>
        public static List<ModelGroup> DecoupleBricks(List<Brick> bricks)
        {
            var newGroups = new List<ModelGroup>();
            
            if (bricks == null || bricks.Count == 0)
            {
                Debug.LogWarning("No bricks to decouple");
                return newGroups;
            }

            Undo.IncrementCurrentGroup();
            int undoGroup = Undo.GetCurrentGroup();
            Undo.SetCurrentGroupName($"Decouple {bricks.Count} Bricks");

            foreach (var brick in bricks)
            {
                var newGroup = DecoupleBrick(brick);
                if (newGroup != null)
                {
                    newGroups.Add(newGroup);
                }
            }

            Undo.CollapseUndoOperations(undoGroup);
            
            return newGroups;
        }

        /// <summary>
        /// Checks if a brick can be decoupled
        /// </summary>
        /// <param name="brick">The brick to check</param>
        /// <returns>True if the brick can be decoupled</returns>
        public static bool CanDecoupleBrick(Brick brick)
        {
            if (brick == null) return false;
            if (ToolsSettings.LockBricksAfterPlacement) return false;
            if (brick.GetComponentInParent<ModelGroup>() == null) return false;
            if (PrefabUtility.IsPartOfPrefabInstance(brick.gameObject)) return false;
            
            return true;
        }
    }
}